---
functional:
  - Пользователь может зарегистрироваться через электронную почту
  - Пользователь может авторизоваться через GitHub
  - Пользователь может авторизоваться через Discord
  - Незарегистрированный пользователь может запустить игру
  - Пользователь может сбросить пароль
  - Пользователь может создать игру
  - Пользователь может выбрать задание из представленного списка
  - Пользователь может выбрать уровень сложности в игре
  - Пользователь может задать время на выполнение задания
  - Пользователь может выбрать противника бота
  - Пользователь может выбрать другого игрока в качестве противника
  - Пользователь может выбрать в качестве противника друга из списка
  - Пользователь может выбрать игру по тегам
  - Пользователь может прочитать руководство к выполнению задания
  - Пользователь может выбрать язык для прочтения задания (EN, RU)
  - Пользователь может выбрать язык для решения задач (Clojure, C++, C#, Dart, Elixir, Haskell, Go, Java, Node.JS, Kotlin, Php, Phyton, Ruby, Rust, Typescript)
  - Пользователь может удалять, вставлять, писать данные в редакторе кода
  - Пользователь может менять язык для решения задач в процессе игры из списка предложенных языков (Clojure, C++, C#, Dart, Elixir, Haskell, Go, Java, Node.JS, Kotlin, Php, Phyton, Ruby, Rust, Typescript)
  - Пользователь может видеть информацию о сопернике
  - Пользователь может сдаться
  - Пользователь может сбросить решение в редакторе кода 
  - Пользователь может проверить решение
  - Пользователь может вернуться в игру пока не вышло время
  - Пользователь может вернуться на главную страницу после завершения игры
  - Пользователь может присоединиться к игре, которую создал другой пользователь
  - Пользователь может просматривать таблицу лидеров (за все время, за месяц, за неделю)
  - Пользователь может просматривать свою статистику
  - Пользователь может просматривать завершенные игры
  - Пользователь может поменять свой никнейм 
  - Пользователь может выбрать звука для окончания раунда
  - Пользователь может регулировать громкость звука уведомлений
  - Пользователь может найти другого пользователя по никнейму
  - Пользователь может добавить в друзья другого пользователя
  - Пользователь может видеть количество пользователей онлайн
  - Пользователь может просматривать турниры
  - Пользователь может просматривать список задач, которые создали другие пользователи
  - Пользователь может создать свою задачу
  - Пользователь может создать свое задание
  - Пользователь может создать свой турнир 
non-functional:
  - Дизайн сайта должен быть адаптивным для всех расширений экранов
  - Сайт должен быть крос-браузерным. Корректно отображать информацию без замедления производительности с последними версиями баузеров (Google Ghrome, Safari, Firefox), а так же на мобильных устройствах
  - Сайт должен быть отказоустойчив. Система должна продолжать функционировать при выходе из строя одного из компонента и возможности быстрого восстановления
  - Сайт должен быть локализован. Должен поддерживать несколько языов, для доступности пользователей из других стран
  - Сайт должен обрабатывать 1000 одновременных пользователей без значительного ухудшения скорости загрузки
  - Сайт должен быть доступен для пользователей большую часть времени 
  - Сайт должен быть удобным в использовании, дизайн интуитивно понятен с простой навигацией
  - Сайт должен защищать личные данные пользователей
implicit:
  - Дизайн сайта должен быть современным и привлекательным, создавать положительное впечатление у пользователей
  - Возможность коммуникации между пользователями в виде чата, форума или комментариев, для обмена опытом и общения
  - Поддержка обратной связи между пользователями и командой разработки для реагирования на возможные предложения по улучшению продукта
  - Поддержка различных языков программирования, а не только базовых, для большей вовлеченности пользователей
