---
functional:
  - Пользователь имеет возможность регистрации и авторизации на сайте используя свой e-mail, или через свой аккаунт в GitHub.
  - Пользователь может попробавть сыграть тестовую игру без регистрации, при этом игра и соперник выберутся рандомно системой.
  - Пользователь может писать код для решения задачи на любом выбранном им языке и менять его в процессе игр.
  - Во время игры, пользователь имеет возможность общаться с соперником в чате их игры, сдаться или перезапустить игру сначала.
  - Пользователь может просматривать таблицу рейтинга с достижениями игроков.
  - Пользователь имеет возможность просматривать любую уже оконченную игру.
  - Пользователь может создавать игры разной тематики, уровня сложности, максимального времени игры и выбора соперника.
  - Пользователь может видеть всех игроков, находящихся сейчас на сайте.
  - После прохождения игры пользователь может сыграть в матч-реванш или вернуться в основное меню игры.
  - Пользователь может просматривать и создавать новые задания для игры.
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть удобным на мобильном устройстве.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей).
implicit:
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Пользователь должен иметь возможность переключать/менять язык сайта на стартовой странице или в личных настройках.
  - Пользователю должно быть предложено обучение по использованию сайта.
